---
- name: Checking ACI Fabric Best Practices
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      host: "{{ aci_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      validate_certs: no
      state: present
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Get Fabric Version
      aci_rest:
        host: "{{ aci_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        path: /api/node/class/firmwareRunning.json
      register: aci_ver
      no_log: False



    - name: Compare Fabric devices code version  with Standards
      
      assert:
        quiet: yes
        that: "item.firmwareRunning.attributes.peVer == bp_recommended.apic_version"
        success_msg: "S"
        fail_msg: "\n The ACI version on {{item.firmwareRunning.attributes.dn}} is {{ item.firmwareRunning.attributes.peVer }}. Best Practices recommends version is {{bp_recommended.apic_version}}"
      loop: "{{aci_ver.imdata | list}}"
      loop_control:
        label: "{{ item.firmwareRunning.attributes.dn}}"
      ignore_errors: true