---

- name: Checking ACI Fabric Best Practices
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      host: "{{ aci_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      validate_certs: no
      state: present
   # ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Get EP Loop protection
      aci_rest:
        host: "{{ aci_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        path: /api/node/mo/uni/infra.json?query-target=children&target-subtree-class=epLoopProtectP
      register: ep_loop
      tags: global

    - name: Compare EP Loop protection with Best Practices
      assert:
        that: "ep_loop.imdata[0].epLoopProtectP.attributes.adminSt == bp_recommended.ep_loop and ep_loop.imdata[0].epLoopProtectP.attributes.action == ''"
        success_msg: "EP Loop protection is configured according to Best Practices"
        fail_msg: "EP Loop protection is NOT configured according to Best Practices; adminSt currently set to: {{ ep_loop.imdata[0].epLoopProtectP.attributes.adminSt }} with action set to: {{ ep_loop.imdata[0].epLoopProtectP.attributes.action }}; action should be NULL"
      ignore_errors: true
      tags: global

    - name: Debug
      debug:
        msg: "Value: {{ep_loop.imdata[0].epLoopProtectP.attributes.adminSt }} result {{ep_loop.imdata[0].epLoopProtectP.attributes.adminSt == bp_recommended.ep_loop}} with action = {{ ep_loop.imdata[0].epLoopProtectP.attributes.action }}"
      #when: playbook_debug is defined
      tags: global