---

- name: Checking ACI Fabric Best Practices
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      host: "{{ aci_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      validate_certs: no
      state: present
   # ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Get Port Tracking
      aci_rest:
        host: "{{ aci_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        path: /api/node/mo/uni/infra/trackEqptFabP-default.json
      register: port_track
      tags: global

    - name: Compare Port Tracking with Best Practices
      assert:
        that: "port_track.imdata[0].infraPortTrackPol.attributes.adminSt == bp_recommended.port_track"
        success_msg: "Port Tracking is configured according to Best Practices"
        fail_msg: "Port Tracking is NOT configured according to Best Practices; currently set to: {{ port_track.imdata[0].infraPortTrackPol.attributes.adminSt }} "
      ignore_errors: true
      tags: global

    - name: Debug
      debug:
        msg: "Value: {{port_track.imdata[0].infraPortTrackPol.attributes.adminSt }} result {{port_track.imdata[0].infraPortTrackPol.attributes.adminSt == bp_recommended.port_track}}"
      #when: playbook_debug is defined
      tags: global
