
---

- name: Configure APIC Health Check
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      validate_certs: no

  tasks:     
    - name: Get Global MCP information
      aci_rest:
        <<: *aci_login
        path: /api/node/mo/uni/infra/qosinst-default.json
      register: preserve_qos
      delegate_to: localhost

    - name: Compare Preserve QoS setting with Best Practices
      assert:
        that: "preserve_qos.imdata[0].qosInstPol.attributes.ctrl == bp_recommended.preserve_qos"
        success_msg: "Preserve QoS is configured according to Best Practices"
        fail_msg: "Preserve QoS is NOT configured according to Best Practices; current value =: {{ preserve_qos.imdata[0].qosInstPol.attributes.ctrl }}; Best Practice value =: {{ bp_recommended.preserve_qos }}"
      ignore_errors: true
      tags: global

    - name: Debug
      debug:
        msg: "Value: {{ preserve_qos.imdata[0].qosInstPol.attributes.ctrl }} result {{ preserve_qos.imdata[0].qosInstPol.attributes.ctrl == bp_recommended.preserve_qos }}"
      #when: playbook_debug is defined
      tags: global


      
      
