
---

- name: Configure APIC Health Check
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      validate_certs: no

  tasks:     
    - name: Get Interface MCP information
      aci_rest:
        <<: *aci_login
        path: /api/node/mo/uni/infra.json?query-target=children&target-subtree-class=mcpIfPol
      register: MCP
      delegate_to: localhost
      
      
      
 #   - name: Compare VRF settings with Best Practices
  #    fail:
 #       msg: "{{item.fvCtx.attributes.name}} VRF is NOT configured according to Best Practices; current setting are:
 #                policy control enforcement preference: {{ item.fvCtx.attributes.pcEnfPref }} AND  
 #                policy control enforcement direction: {{ item.fvCtx.attributes.pcEnfDir }}"
 #                
 #     when: item.fvCtx.attributes.pcEnfPref != bp_recommended.vrf.enforced or item.fvCtx.attributes.pcEnfDir != bp_recommended.vrf.enforcement_direction 
 #     loop: "{{vrfs.imdata}}"
  #    loop_control:
  #      label: "{{ item.fvCtx.attributes.name }}"
 #     ignore_errors: true
 #     tags: vrf
      
    - name: Compare MCP policie settings with Best Practices
     
      assert:
        quiet: yes
        that: "item.mcpIfPol.attributes.adminSt == bp_recommended.interface_MCP"
        success_msg: "S"
        fail_msg: "{{item.mcpIfPol.attributes.name}} MCP policy is NOT configured according to Best Practices; current setting is: {{ item.mcpIfPol.attributes.adminSt}} "
      
      loop: "{{MCP.imdata}}"
      loop_control:
        label: "{{ item.mcpIfPol.attributes.name }}"
      ignore_errors: true
      tags: vrf 
      

