---

- name: Checking ACI Fabric Best Practices
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      host: "{{ aci_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      validate_certs: no
      state: present
   # ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Get All VRF info from ACI
      aci_rest:
        host: "{{ aci_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        path: /api/node/class/fvCtx.json
      register: vrfs
      tags: vrf

    - name: Compare VRF settings with Best Practices
     
      assert:
        quiet: yes
        that: "item.fvCtx.attributes.pcEnfPref == bp_recommended.vrf.enforced and item.fvCtx.attributes.pcEnfDir == bp_recommended.vrf.enforcement_direction"
        success_msg: "S"
        fail_msg: "{{item.fvCtx.attributes.name}} VRF is NOT configured according to Best Practices; current setting are:
                 policy control enforcement preference: {{ item.fvCtx.attributes.pcEnfPref }} AND  
                 policy control enforcement direction: {{ item.fvCtx.attributes.pcEnfDir }}"
      
      loop: "{{vrfs.imdata}}"
      loop_control:
        label: "{{ item.fvCtx.attributes.name }}"
      ignore_errors: true
      tags: vrf
      
    - name: Compare VRF Dataplane Learning settings with Best Practices
      
      assert:
        quiet: yes
        that: "item.fvCtx.attributes.ipDataPlaneLearning == bp_recommended.vrf.dataplane_learning "
        success_msg: "S"
        fail_msg: "{{item.fvCtx.attributes.name}} VRF Dataplane Learning is NOT configured according to Best Practices, current setting for Data Plane Learning: {{ item.fvCtx.attributes.ipDataPlaneLearning}}"
      
      
      loop: "{{vrfs.imdata}}"
      loop_control:
        label: "{{ item.fvCtx.attributes.name }}"
      ignore_errors: true
      tags: vrf