---

- name: Checking ACI Fabric Best Practices
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      host: "{{ aci_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      validate_certs: no
      state: present
   # ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Get Enforce Subnet Check
      aci_rest:
        host: "{{ aci_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        path: /api/node/mo/uni/infra/settings.json
      register: enforce_subnet_check
      tags: global

    - name: Compare Enforce Subnet Check with Best Practices
      assert:
        that: "enforce_subnet_check.imdata[0].infraSetPol.attributes.enforceSubnetCheck | bool == bp_recommended.enforce_subnet_check"
        success_msg: "Enforce Subnet Check is configured according to Best Practices"
        fail_msg: "Enforce Subnet Check is NOT configured according to Best Practices; current setting is: {{ enforce_subnet_check.imdata[0].infraSetPol.attributes.enforceSubnetCheck | bool }}"
      ignore_errors: true
      tags: global

    - name: Debug
      debug:
        msg: "Value: {{enforce_subnet_check.imdata[0].infraSetPol.attributes.enforceSubnetCheck | bool }} result {{enforce_subnet_check.imdata[0].infraSetPol.attributes.enforceSubnetCheck | bool == bp_recommended.enforce_subnet_check}}"
      #when: playbook_debug is defined
      tags: global