
---

- name: Configure APIC Health Check
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      validate_certs: no

  tasks:     
    - name: Get Interface MCP information
      aci_rest:
        <<: *aci_login
        path: /api/node/mo/uni/infra.json?query-target=children&target-subtree-class=mcpIfPol
      register: interface_MCP
      delegate_to: localhost
      
    - name: Compare interface MCP setting with Best Practices
      assert:
        that: "interface_MCP.imdata[0].mcpIfPol.attributes.adminSt == bp_recommended.interface_MCP"
        success_msg: "Interface MCP is configured according to Best Practices"
        fail_msg: "Interface MCP is NOT configured according to Best Practices; interface value =: {{interface_MCP.imdata[0].mcpIfPol.attributes.adminSt}}; Best Practice value =: {{ bp_recommended.interface_MCP }}"
      ignore_errors: true
      tags: global

    - name: Debug
      debug:
        msg: "Value: {{interface_MCP.imdata[0].mcpIfPol.attributes.adminSt}} result {{interface_MCP.imdata[0].mcpIfPol.attributes.adminSt == bp_recommended.interface_MCP}}"
      #when: playbook_debug is defined
      tags: global

