---

- name: Checking ACI Fabric Best Practices
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      host: "{{ aci_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      validate_certs: no
      state: present
   # ansible_python_interpreter: /usr/bin/python3
   
  tasks:
    - name: Get DOM setting
      aci_rest:
        host: "{{ aci_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        path: /api/node/class/fabricNodeControl.json
      register: DOM_feature       
      tags: global  
    
    - name: Compare DOM feature setting  with Best Practices
      assert:
        that: "DOM_feature.imdata[0].fabricNodeControl.attributes.featureSel == bp_recommended.DOM_feature"
        success_msg: "DOM feature setting is configured according to Best Practices"
        fail_msg: "DOM feature setting is NOT configured according to Best Practices; DOM feature setting is =: {{ DOM_feature.imdata[0].fabricNodeControl.attributes.featureSel }} best practice is =: {{ bp_recommended.DOM_feature }} "
      ignore_errors: true
      tags: global
      
    - name: Debug
      debug:
        msg: "Value: {{ DOM_feature.imdata[0].fabricNodeControl.attributes.featureSel }} result {{DOM_feature.imdata[0].fabricNodeControl.attributes.featureSel == bp_recommended.DOM_feature }}"
      #when: playbook_debug is defined
      tags: global
