---

- name: Checking ACI Fabric Best Practices
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      host: "{{ aci_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      validate_certs: no
      state: present
   # ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Get BFD ISIS setting
      aci_rest:
        host: "{{ aci_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        path: /api/node/mo/uni/fabric/l3IfP-default.json
        #path: /api/node/mo/uni/fabric.json?query-target=subtree&target-subtree-class=l3IfPol
      register: bfdisis
      tags: global  
    
    - name: Compare BFD ISIS setting with Best Practices
      assert:
        that: "bfdisis.imdata[0].l3IfPol.attributes.bfdIsis == bp_recommended.bfdisis"
        success_msg: "BFD ISIS is configured according to Best Practices"
        fail_msg: "BFD ISIS  is NOT configured according to Best Practices; Fabric value =: {{bfdisis.imdata[0].l3IfPol.attributes.bfdIsis}}; Best Practice value =: {{ bp_recommended.bfdisis }}"
      ignore_errors: true
      tags: global
      
    - name: Debug
      debug:
        msg: "Value: {{bfdisis.imdata[0].l3IfPol.attributes.bfdIsis}} result {{bfdisis.imdata[0].l3IfPol.attributes.bfdIsis | int == bp_recommended.bfdisis}}"
      #when: playbook_debug is defined
      tags: global
