---

- name: Checking ACI Fabric Best Practices
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      host: "{{ aci_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      validate_certs: no
      state: present
   # ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Get PTP
      aci_rest:
        host: "{{ aci_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        path: /api/node/mo/uni/fabric/ptpmode.json
      register: ptp
      tags: global

    - name: Compare PTP with Best Practices
      assert:
        that: "ptp.imdata[0].latencyPtpMode.attributes.state == bp_recommended.ptp"
        success_msg: "PTP is configured according to Best Practices"
        fail_msg: "PTP is NOT configured according to Best Practices; currently set to: {{ ptp.imdata[0].latencyPtpMode.attributes.state }}"
      ignore_errors: true
      tags: global

    - name: Debug
      debug:
        msg: "Value: {{ptp.imdata[0].latencyPtpMode.attributes.state }} result {{ptp.imdata[0].latencyPtpMode.attributes.state == bp_recommended.ptp}}"
     # when: playbook_debug is defined
      tags: global