---

- name: Checking ACI Fabric Best Practices
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      host: "{{ aci_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      validate_certs: no
      state: present
   # ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Get Disable Remote EP Learn
      aci_rest:
        host: "{{ aci_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        path: /api/node/mo/uni/infra/settings.json
      register: remote_ep_learn
      tags: global

    - name: Compare Disable Remote EP Learn with Best Practices
      assert:
        that: "remote_ep_learn.imdata[0].infraSetPol.attributes.unicastXrEpLearnDisable | bool == bp_recommended.remote_ep_learn"
        success_msg: "Disable Remote EP Learn is configured according to Best Practices"
        fail_msg: "Disable Remote EP Learn is NOT configured according to Best Practices, current setting is: {{ remote_ep_learn.imdata[0].infraSetPol.attributes.unicastXrEpLearnDisable | bool }}"
      ignore_errors: true
      tags: global

    - name: Debug
      debug:
        msg: "Value: {{remote_ep_learn.imdata[0].infraSetPol.attributes.unicastXrEpLearnDisable | bool }} result {{remote_ep_learn.imdata[0].infraSetPol.attributes.unicastXrEpLearnDisable | bool == bp_recommended.remote_ep_learn}}"
      #when: playbook_debug is defined
      tags: global
