
---

- name: Configure APIC Health Check
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      validate_certs: no

  tasks:     
    - name: Get Global MCP information
      aci_rest:
        <<: *aci_login
        path: /api/node/mo/uni/infra/mcpInstP-default.json
      register: Global_MCP
      delegate_to: localhost

    - name: Compare Global MCP setting with Best Practices
      assert:
        that: "Global_MCP.imdata[0].mcpInstPol.attributes.adminSt == bp_recommended.Global_MCP"
        success_msg: "Global MCP is configured according to Best Practices"
        fail_msg: "Global MCP is NOT configured according to Best Practices; current value =: {{ Global_MCP.imdata[0].mcpInstPol.attributes.adminSt }}; Best Practice value =: {{ bp_recommended.Global_MCP }}"
      ignore_errors: true
      tags: global

    - name: Debug
      debug:
        msg: "Value: {{ Global_MCP.imdata[0].mcpInstPol.attributes.adminSt }} result {{ Global_MCP.imdata[0].mcpInstPol.attributes.adminSt == bp_recommended.Global_MCP}}"
      #when: playbook_debug is defined
      tags: global


      
      
