---

- name: Checking ACI Fabric Best Practices
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      host: "{{ aci_hostname }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      validate_certs: no
      state: present
   # ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Get IP Aging
      aci_rest:
        host: "{{ aci_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        path: /api/node/mo/uni/infra.json?query-target=children&target-subtree-class=epIpAgingP
      register: ip_aging
      tags: global

    - name: Compare IP Aging with Best Practices
      assert:
        that: "ip_aging.imdata[0].epIpAgingP.attributes.adminSt == bp_recommended.ip_aging"
        success_msg: "IP Aging is configured according to Best Practices"
        fail_msg: "IP Aging is NOT configured according to Best Practices; currently  set to: {{ ip_aging.imdata[0].epIpAgingP.attributes.adminSt }}"
      ignore_errors: true
      tags: global

    - name: Debug
      debug:
        msg: "Value: {{ip_aging.imdata[0].epIpAgingP.attributes.adminSt }} result {{ip_aging.imdata[0].epIpAgingP.attributes.adminSt == bp_recommended.ip_aging}}"
      #when: playbook_debug is defined
      tags: global