
---

- name: Configure APIC Health Check
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      validate_certs: no

  tasks:     
    - name: Get Password Encryptioom
      aci_rest:
        <<: *aci_login
        path: /api/node/mo/uni/exportcryptkey.json?query-target=children&target-subtree-class=relnFrom
     register: password_encrypt
     delegate_to: localhost

    - debug:
        var: password_encrypt


      
      
