
---

- name: Configure APIC Health Check
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      validate_certs: no

  tasks:     
    - name: Get IP Aging setting
      aci_rest:
        <<: *aci_login
        path: /api/node/mo/uni/infra.json?query-target=children&target-subtree-class=epIpAgingP
      register: IP_aging
      delegate_to: localhost

    - debug:
        var: IP_aging


      
      
