
---

- name: Configure APIC Health Check
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      validate_certs: no

  tasks:     
    - name: Get Coop Group Type
      aci_rest:
        <<: *aci_login
        path: /api/node/mo/uni/fabric/pol-default.json
      register: coop_type
      delegate_to: localhost

    - debug:
        var: coop_type


      
      
