
---

- name: Configure APIC Health Check
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      validate_certs: no

  tasks:     
    - name: Get Fabric Version
      aci_rest:
         <<: *aci_login
         method: get
         path: /api/node/class/firmwareRunning.json
      register: aci_version
      delegate_to: localhost
      
      
    - debug:
        var: aci_version


      
      
