
---

- name: Configure APIC Health Check
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      validate_certs: no

  tasks:     
    - name: Get Disable Remote EP Learn
      aci_rest:
        <<: *aci_login
        path: /api/node/mo/uni/infra/settings.json
      register: remote_ep_learn
      delegate_to: localhost

      
    - debug:
        var: remote_ep_learn


      
      
