
---

- name: Configure APIC Health Check
  hosts: '*apic1'
  connection: local
  gather_facts: no
  vars:
    aci_login: &aci_login
      hostname: '{{ aci_hostname }}'
      username: '{{ aci_username }}'
      password: '{{ aci_password }}'
      validate_certs: no

  tasks:     
    - name: Get Control Plane MTU
      aci_rest:
        <<: *aci_login
        method: get
        path: /api/node/mo/uni/infra/CPMtu.json
      register: cpmtu
      delegate_to: localhost
      
    - debug:
         var: cpmtu
         

      
      
